server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Customer PWA Frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Dedicated Web Admin Dashboard Route
    location /admin {
        try_files $uri $uri/ /index.html;
    }

    # API Reverse Proxy to Go API Gateway
    location /api/ {
        proxy_pass http://api-gateway:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # MinIO Storage Proxy for Media Receipts & Images
    location /media/ {
        proxy_pass http://minio:9000/desa-media/;
    }
}
